### ISSUE TITLE
Application fails to run

### ISSUE THREAD

**Issue by kamen-al-gopin** [dabrowskimarcin/VehicleService#1]
If you try to run the app with `./gradlew run`, that would fail with
```
Caused by: java.lang.ClassNotFoundException: io.micronaut.http.client.exceptions.HttpClientResponseException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        ... 90 common frames omitted
```

The issue is here https://github.com/dabrowskimarcin/VehicleService/blob/7b98d91dff88ebc083fd2741411f70a9bce9bae7/build.gradle#L33
The micronaut http client library is needed not just for the tests but also for the production code.

```
testImplementation("io.micronaut:micronaut-http-client")
```
should be 
```
implementation("io.micronaut:micronaut-http-client")
```

**Comment by dabrowskimarcin** [comment]
I started this project from Intelij and I had no problems but you're right. Your fix helped and now application run directly from ./gradlew run
